apiVersion: apps/v1
kind: Deployment
metadata:
  name: netg
spec:
  replicas: 3
  selector:
    matchLabels:
      app: netg
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: netg
        image: onurkaroff/netg_mobile:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: "5Gi"
          requests:
            cpu: "0.5"
            memory: "3Gi"
        ports:
        - containerPort: 8000
        securityContext:
          runAsNonRoot: true
